dist: jammy
language: ruby
rvm:
  - 3.4.2
env:
  global:
    - RAILS_ENV=test
    - NODE_ENV=production
    - PGUSER=postgres
    - PGHOST=127.0.0.1
    - PGPORT=5432
    - POSTGRES_DB=grubpjx_test
    - NODE_OPTIONS="--max-old-space-size=6000"
    - PSQL_PAGER=""
before_install:
  - sudo apt-get update
  - sudo apt-get install -y postgresql postgresql-contrib
  - sudo apt-get -y install elasticsearch
  - 'sudo sed -i "s/enabled: true/enabled: false/g" /etc/elasticsearch/elasticsearch.yml'
  - sudo systemctl start elasticsearch
  - until curl --silent -XGET --fail http://localhost:9200; do printf '...\n'; sleep 2; done
  - echo "Downloading CodeClimate test reporter..."
  - mkdir -p tmp/
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o tmp/cc-test-reporter
  - chmod +x tmp/cc-test-reporter
  - echo "Waiting for PostgreSQL readiness..."
  - until pg_isready -h "$PGHOST" -p "$PGPORT" -U "$PGUSER"; do echo "Waiting..."; sleep 2; done
  - echo "Creating test database..."
  - psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d postgres -c "CREATE DATABASE $POSTGRES_DB;" || true
install:
  - gem install bundler
  - bundle install
  - if [ -d "client" ]; then cd client && npm install && cd ..; fi
  - if [ -d "client/v2" ]; then cd client/v2 && npm install && cd ../..; fi
before_script:
  - echo "Preparing test environment..."
  - bundle exec rake db:test:prepare || echo "Skipping db:test:prepare"
  - ./tmp/cc-test-reporter before-build
script:
  - bundle exec rake test
  - if [ -d "client" ]; then cd client && npm test && cd ..; fi
after_script:
  - ./tmp/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  bundler: true
  directories:
    - node_modules
    - client/node_modules
    - client/v2/node_modules
branches:
  only:
    - main
    - master
    - develop
