dist: jammy
language: bash

before_install:
  - sudo apt-get update
  - sudo apt-get install -y postgresql postgresql-contrib

before_script:
  - sudo systemctl start postgresql
  - sudo systemctl status postgresql
  - sudo -u postgres psql -c "CREATE DATABASE testdb;"
  - sudo -u postgres psql -c "SELECT version();"

script:
  - echo "PostgreSQL is working"
